// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN13n2n3l4JOCcJ02xvNFCfkCTuulKSrE',
    appId: '1:343568247437:web:6c2de11101d297bfed90c4',
    messagingSenderId: '343568247437',
    projectId: 'the-saviours',
    authDomain: 'the-saviours.firebaseapp.com',
    storageBucket: 'the-saviours.firebasestorage.app',
    measurementId: 'G-GQLXY2WK6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQIH9OY9hboSt5qCDIvHYeuepJBJh0nMk',
    appId: '1:343568247437:android:ea96141c26a91806ed90c4',
    messagingSenderId: '343568247437',
    projectId: 'the-saviours',
    storageBucket: 'the-saviours.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN13n2n3l4JOCcJ02xvNFCfkCTuulKSrE',
    appId: '1:343568247437:web:6c2de11101d297bfed90c4',
    messagingSenderId: '343568247437',
    projectId: 'the-saviours',
    storageBucket: 'the-saviours.firebasestorage.app',
    iosBundleId: 'com.example.the_saviours',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN13n2n3l4JOCcJ02xvNFCfkCTuulKSrE',
    appId: '1:343568247437:web:6c2de11101d297bfed90c4',
    messagingSenderId: '343568247437',
    projectId: 'the-saviours',
    storageBucket: 'the-saviours.firebasestorage.app',
    iosBundleId: 'com.example.the_saviours',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN13n2n3l4JOCcJ02xvNFCfkCTuulKSrE',
    appId: '1:343568247437:web:6c2de11101d297bfed90c4',
    messagingSenderId: '343568247437',
    projectId: 'the-saviours',
    authDomain: 'the-saviours.firebaseapp.com',
    storageBucket: 'the-saviours.firebasestorage.app',
    measurementId: 'G-GQLXY2WK6H',
  );
}