// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCWGR0TYfQT6iKy3EuqVG-Pp2XnChzcyg',
    appId: '1:430748353801:web:f82c649952c2b9caad7fd8',
    messagingSenderId: '430748353801',
    projectId: 'greenwave-544ab',
    authDomain: 'greenwave-544ab.firebaseapp.com',
    storageBucket: 'greenwave-544ab.firebasestorage.app',
    measurementId: 'G-9Z1RXJRR56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgJ8i3o-UV8c46PmdaohbcgwnKg6jcnV8',
    appId: '1:430748353801:android:9e3531af3e897ef6ad7fd8',
    messagingSenderId: '430748353801',
    projectId: 'greenwave-544ab',
    storageBucket: 'greenwave-544ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6go6T_pcl8IIY3T0Y3-hmevnkokCDQkU',
    appId: '1:430748353801:ios:d78d70d8a46a285dad7fd8',
    messagingSenderId: '430748353801',
    projectId: 'greenwave-544ab',
    storageBucket: 'greenwave-544ab.firebasestorage.app',
    iosBundleId: 'com.example.greenWave',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6go6T_pcl8IIY3T0Y3-hmevnkokCDQkU',
    appId: '1:430748353801:ios:d78d70d8a46a285dad7fd8',
    messagingSenderId: '430748353801',
    projectId: 'greenwave-544ab',
    storageBucket: 'greenwave-544ab.firebasestorage.app',
    iosBundleId: 'com.example.greenWave',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCWGR0TYfQT6iKy3EuqVG-Pp2XnChzcyg',
    appId: '1:430748353801:web:594afa69e2f31ad1ad7fd8',
    messagingSenderId: '430748353801',
    projectId: 'greenwave-544ab',
    authDomain: 'greenwave-544ab.firebaseapp.com',
    storageBucket: 'greenwave-544ab.firebasestorage.app',
    measurementId: 'G-RJ6Z7LH8RD',
  );
}
